services:
  api:
    build:
      context: .
      dockerfile: TaskService.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionString__Default=Host=db;Port=5432;Database=tasks;Username=postgres;Password=postgres

  db:
    image: postgres:16

    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
